#### Crear usuario
POST http://localhost:3005/simu/auth/registro
Content-Type: application/json

{
  "nombre": "Juan",
  "correo": "juan@gmail.com",
  "contraseña": "12345678"
} 


#### Peticion get
GET http://localhost:3005/simu/auth/